CREATE TABLE [Retail].[Customer] (
    [Id]                 INT              IDENTITY (1, 1) NOT NULL,
    [CustomerGuid]       UNIQUEIDENTIFIER CONSTRAINT [DF_Customer_CustomerGuid] DEFAULT (newid()) NOT NULL,
    [UserName]           NVARCHAR (50)    NULL,
    [Title]              NVARCHAR (10)    NULL,
    [GivenName]          NVARCHAR (50)    NULL,
    [SurName]            NVARCHAR (50)    NULL,
    [MiddleInitial]      NVARCHAR (50)    NULL,
    [DateOfBirth]        DATETIME         NULL,
    [Sex]                NVARCHAR (10)    NULL,
    [Gender]             NVARCHAR (10)    NULL,
    [Country]            NVARCHAR (50)    NULL,
    [Email]              NVARCHAR (150)   NULL,
    [MobileNumber]       NVARCHAR (50)    NULL,
    [State]              NVARCHAR (50)    NULL,
    [City]               NVARCHAR (50)    NULL,
    [RegisterIp]         NVARCHAR (50)    NULL,
    [AuthProvider]       NVARCHAR (50)    NULL,
    [Occupation]         NVARCHAR (255)   NULL,
    [HosueholdType]      NVARCHAR (50)    CONSTRAINT [DF_Customer_HosueholdType] DEFAULT ((0)) NULL,
    [AgeGroupType]       NVARCHAR (50)    NULL,
    [HouseHoldId]        INT              NULL,
    [AgeGroupId]         INT              NULL,
    [WeekDay]            INT              NULL,
    [MonthDay]           INT              NULL,
    [FortnightStart]     INT              NULL,
    [BiMonthlyStart]     INT              NULL,
    [QuarterMonth]       INT              NULL,
    [QuarterMonthDay]    INT              NULL,
    [SemiAnnualMonth]    INT              NULL,
    [SemiAnnualMonthDay] INT              NULL,
    [AnnualMonth]        INT              NULL,
    [AnnualMonthDay]     INT              NULL,
    [DataGenPeriodStart] DATETIME         NULL,
    [DataGenPeriodEnd]   DATETIME         NULL,
    [CeleberatoryBuys]   INT              NULL,
    [VacationDays]       INT              NULL,
    [TeenageCount]       INT              NULL,
    [InfantCount]        INT              NULL,
    [ChildCount]         INT              NULL,
    [ElderCount]         INT              NULL,
    [Christmas]          INT              CONSTRAINT [DF_Customer_Christmas] DEFAULT ((0)) NOT NULL,
    [CNY]                INT              CONSTRAINT [DF_Customer_CNY] DEFAULT ((0)) NOT NULL,
    [Birthday]           INT              CONSTRAINT [DF_Customer_Birthday] DEFAULT ((0)) NOT NULL,
    [Medical]            INT              CONSTRAINT [DF_Customer_Medical] DEFAULT ((0)) NOT NULL,
    [Celebratory]        INT              CONSTRAINT [DF_Customer_Celebratory] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0 - Individual, 1 - HouseMaker', @level0type = N'SCHEMA', @level0name = N'Retail', @level1type = N'TABLE', @level1name = N'Customer', @level2type = N'COLUMN', @level2name = N'HosueholdType';

